
platform :ios, '10.0'

target 'YJAwesome' do
  
  use_frameworks!

#基础组件
  pod 'Alamofire'
  pod 'Moya'
  pod 'SnapKit'
  pod 'R.swift'
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftyRSA'
#第三方服务
  pod 'GT3Captcha-iOS'
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
end
